name: Schedule Builds

on:
  # allow rebuilding manually
  workflow_dispatch:
  # pre-build sstate regularly
  schedule:
    - cron: '30 2 * * *'

jobs:
  build:
    name: Schedule Builds
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Trigger master build
        run: gh workflow run build --ref master
