# This file was generated by tools/update/update.py

require python3-labgrid.inc

# Version v25.0-146-gf63dfd7 commited 2025-11-04 10:47:29 +0100
PV = "25.0+git"
SRCBRANCH = "master"
SRCREV = "f63dfd70a5da2c7007ee8c320fa969df2c0bf16e"

LABGRID_USE_DEVEL_VERSION[doc] = "Global switch to enable labgrid development (git) version"
LABGRID_USE_DEVEL_VERSION ??= "-1"
DEFAULT_PREFERENCE ??= "${LABGRID_USE_DEVEL_VERSION}"
