# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.75.1 released 2025-09-26T09:13:21.
SRC_URI[sha256sum] = "2be3f20b7b93e6e691a0bc761fd7e9996a940b4c96c68f6ca4f7fbc47c3f4b64"
