# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.75.0 released 2025-09-16T09:24:56.
SRC_URI[sha256sum] = "d521973a343806a8384bf87ceae93cf2e9f10f8fab02c12be7a2e3d5d0e4e68f"
