# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.78.1 released 2026-02-20T01:21:52.
SRC_URI[sha256sum] = "3a75296ae0e42c842c65055e0b8e67656b6a02290865474fc464f13cabe9df94"
