# This file was generated by tools/update/update.py

require python3-labgrid.inc

# Version v25.0-132-gfd3f528 commited 2025-10-10 13:48:20 +0200
PV = "25.0+git"
SRCBRANCH = "master"
SRCREV = "fd3f52800fbc89811cd19ad440851f39fe78a09f"

LABGRID_USE_DEVEL_VERSION[doc] = "Global switch to enable labgrid development (git) version"
LABGRID_USE_DEVEL_VERSION ??= "-1"
DEFAULT_PREFERENCE ??= "${LABGRID_USE_DEVEL_VERSION}"
