# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.78.1 released 2026-02-20T01:21:49.
SRC_URI[sha256sum] = "224c0d604207954923fd6f8dbec541e0976a64ab1be65d2ee40844ce16c762ab"
