# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.78.0 released 2026-02-06T10:01:52.
SRC_URI[sha256sum] = "e6e60c0b85dbcdf963b4d4d150c0f1d238ba891d805b575c52c0365d07fc0c40"
