# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.76.0 released 2025-10-21T16:28:57.
SRC_URI[sha256sum] = "e0e7e49921c2ee951e5ddff0bdbacbd1ac1a70888beb61d567f3d01b799decb1"
