# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.78.0 released 2026-02-06T10:01:48.
SRC_URI[sha256sum] = "e44fe0478d78b29075c6d258b8c5107619c06465c013ab1849e5bef493af153e"
