# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.75.1 released 2025-09-26T09:13:20.
SRC_URI[sha256sum] = "e0caa06d4de3eb62d3fdc54e5c9dc9003aa3ee21e9c50f5d3538aea854d276f2"
