# This file was generated by tools/update/update.py

require python3-grpcio-channelz.inc

# Version 1.76.0 released 2025-10-21T16:28:56.
SRC_URI[sha256sum] = "2ab15ef7b2252a9ba31df500bbe295ce5310a8b01ea6f6d67a17172d914a41a8"
