# This file was generated by tools/update/update.py

require python3-grpcio-reflection.inc

# Version 1.75.0 released 2025-09-16T09:24:51.
SRC_URI[sha256sum] = "60bb9865f5411ad589420eadcdd7e0c338c0aabedf5d4cd07363d5bf7da9c972"
